#!/bin/sh

title() {
	echo -ne "\033]0;$1\007"
}

timestr() {
	printf "%d:%02d" $(($1/60)) $(($1%60))
}

getchar() {
	read -s -n 1 $@ key
	echo $key
}

disp() {
	echo -e $log
	echo "--------------------------------------------------------------------------------"
	echo -e $console
}

log_echo() {
	log="$log\033[33m$(date "+%r")\033[0m $(echo $@)\n"
}

console_clear() {
	console=""
	clear
}

console_echo() {
	console="$console$(echo $@)\n"
}

title Pomodoro
while true; do
	console_clear
	console_echo -e "\033[1mP\033[0momodoro session (25 min)"
	console_echo -e "\033[1mS\033[0mhort pause (5 min)"
	console_echo -e "\033[1mL\033[0mong pause (10 min)"
	console_echo -e "\033[1mQ\033[0muit"
	disp

	count=0
	choice=""
	while [ $count -eq 0 ]; do
		case $(getchar) in
			p|P)
				count=$((25*60))
				choice_color="91"
				choice="Pomodoro"
				;;
			l|L)
				count=$((10*60))
				choice_color="32"
				choice="Pause"
				;;
			s|S)
				count=$((5*60))
				choice_color="32"
				choice="Pause"
				;;
			q|Q)
				exit 0
				;;
		esac
	done

	console_clear
	log_echo "\033[${choice_color}m$choice\033[0m for $(timestr $count)"
	console_echo -e "\033[1mS\033[0mtop $choice"
	console_echo -e "\033[1m+\033[0m increase timer by one minute"
	console_echo -e "\033[1m-\033[0m decrease timer by one minute"
	disp
	start=$(date +%s)
	remaining=$count
	while [ $remaining -gt 0 ]; do
		cur=$(date +%s)
		remaining=$(($count - ($cur - $start)))
		title "$choice ($(timestr $remaining))"
		case $(getchar -t 1) in
		s|S)
			count=0
			;;
		-)
			count=$(($count-60))
			;;
		+)
			count=$(($count+60))
			;;
		esac
	done
	disp

	log_echo "Over"
	title "$choice over"
	aplay /usr/share/sounds/pomodoro/alert.wav >/dev/null 2>&1&
done
