#!/bin/sh

title() {
	echo -ne "\033]0;$1\007"
}

timestr() {
	printf "%d:%02d" $(($count/60)) $(($count%60))
}

getchar() {
	read -s -n 1 $@ key
	echo $key
}

disp() {
	true
}

log_echo() {
	echo $@
}

console_clear() {
	true
}

console_echo() {
	echo $@
}

title Pomodoro
while true; do
	console_clear
	console_echo -e "\033[1mP\033[0momodoro session (25 min)"
	console_echo -e "\033[1mS\033[0mhort pause (5 min)"
	console_echo -e "\033[1mL\033[0mong pause (10 min)"
	console_echo -e "\033[1mQ\033[0muit"
	console_echo
	disp

	count=0
	choice=""
	while [ $count -eq 0 ]; do
		case $(getchar) in
			p|P)
				count=$((25*60))
				choice="Pomodoro"
				;;
			l|L)
				count=$((10*60))
				choice="Pause"
				;;
			s|S)
				count=$((5*60))
				choice="Pause"
				;;
			q|Q)
				exit 0
				;;
		esac
	done

	date +%r%x
	console_clear
	log_echo "$choice for $(timestr $count)"
	console_echo -e "\033[1mS\033[0mtop $choice"
	console_echo -e "\033[1m+\033[0m increase timer by one minute"
	console_echo -e "\033[1m-\033[0m decrease timer by one minute"
	disp
	while [ $count -gt 0 ]; do
		title "$choice ($(timestr $count))"
		count=$((count - 1))
		case $(getchar -t 1) in
		s|S)
			count=0
			;;
		-)
			count=$(($count-60))
			console_echo $(timestr $count)
			;;
		+)
			count=$(($count+60))
			console_echo $(timestr $count)
			;;
		esac
	done
	disp

	date +%r%x
	echo "$choice over"
	title "$choice over"
	aplay /usr/share/sounds/pomodoro/alert.wav >/dev/null 2>&1&
	echo
done
